server {
    listen 80;
    server_name_in_redirect off;
    access_log  /var/log/nginx/host.access.log  main;
    client_max_body_size 64M;

    root /var/www/html;
    index index.php index.html;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires max;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_read_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_connect_timeout 300;

        fastcgi_param PHP_VALUE "upload_max_filesize=64M \n post_max_size=64M \n max_execution_time=300";
    }

    location ~ ^/(upload|logs)/ {
        deny all;
    }

    location /cache/ {
        allow all;
        try_files $uri =404;
    }
}